import "./globals.css";
import { Pattaya } from "next/font/google";
import Baner from "@/components/Baner";

const font = Pattaya({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Агроусадьба Лесная Сказка",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={font.className}>
        <Baner />

        {children}
      </body>
    </html>
  );
}
