import "./globals.css";
import Baner from "@/components/Baner";
import { Pattaya, Amatic_SC } from "next/font/google";

const pattaya = Pattaya({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-sans-serif",
});

const amatic = Amatic_SC({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-cursive",
});

export const metadata = {
  title: "Агроусадьба Лесная Сказка",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru" className={`${pattaya.variable} ${amatic.variable}`}>
      <body>
        <Baner />

        {children}
      </body>
    </html>
  );
}
